version: "3.8"

services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
  redis:
    image: redis:latest
    environment:
      REDIS_DB: ${REDIS_DB}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_volume:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  psql_volume:
  redis_volume:
